spring:
  profiles:
    active: local
  application:
    name: CloudFileStorage
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_file_storage
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379